---
abstract: 'Testing framework for command line applications inspired by Cram'
author:
  - 'Fabrice Gabolde <fabrice.gabolde@gmail.com>'
build_requires:
  File::Spec: 0
  Test::Exception: 0
  Test::More: 0
  Test::SetupTeardown: 0
configure_requires:
  Module::Build: 0.36_14
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lembas
provides:
  Lembas:
    file: lib/Lembas.pm
    version: 0.001
requires:
  IPC::Run: 0
  List::Util: 0
  Moo::Lax: 0
  Params::Validate: 0
  Test::Builder: 0
  Text::ParseWords: 0
  perl: 5.014
resources:
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/fgabolde/Lembas
version: 0.001
